# Generated by Django 5.1 on 2024-08-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="product_images")),
                (
                    "original_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("discounts", models.CharField(max_length=50)),
                (
                    "discounted_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("reviews", models.FloatField()),
                ("processor", models.CharField(max_length=255)),
                ("ram", models.CharField(max_length=50)),
                ("os", models.CharField(max_length=50)),
                ("ssd", models.CharField(max_length=50)),
                ("display", models.CharField(max_length=50)),
                ("brand", models.CharField(max_length=50)),
            ],
        ),
    ]
